INSERT INTO `ga_role` (`Role_ID`, `Role_Name`) VALUES (1, 'Admin');
INSERT INTO `ga_role` (`Role_ID`, `Role_Name`) VALUES (2, 'Campus Manager');
INSERT INTO `ga_role` (`Role_ID`, `Role_Name`) VALUES (3, 'Responsable pédagogique');
INSERT INTO `ga_role` (`Role_ID`, `Role_Name`) VALUES (4, 'Formateur');
INSERT INTO `ga_role` (`Role_ID`, `Role_Name`) VALUES (5, 'Délégué');
INSERT INTO `ga_role` (`Role_ID`, `Role_Name`) VALUES (6, 'Apprenant');
INSERT INTO `ga_user` (`User_ID`, `User_FirstName`, `User_LastName`, `User_Password`, `User_Activated`, `User_Email`, `Role_ID`) VALUES (NULL, 'admin', 'admin', '$2y$10$L18KlpRry5kjyYg6A1FU8uSj1Znd0VOBqHE7vuEbZk3mMA3MWjoJi', '1', 'admin@admin.fr', '1');
INSERT INTO `ga_class` (`Class_ID`, `Class_Name`, `Class_Start`, `Class_Finish`, `Class_Places`) VALUES (NULL, 'DWMM2', '2024-01-01', '2024-01-12', '15');
INSERT INTO `ga_class` (`Class_ID`, `Class_Name`, `Class_Start`, `Class_Finish`, `Class_Places`) VALUES (NULL, 'DWMM3', '2024-01-01', '2024-01-12', '15');
INSERT INTO `ga_class` (`Class_ID`, `Class_Name`, `Class_Start`, `Class_Finish`, `Class_Places`) VALUES (NULL, 'CDA', '2024-01-01', '2024-01-12', '12');
INSERT INTO `ga_class` (`Class_ID`, `Class_Name`, `Class_Start`, `Class_Finish`, `Class_Places`) VALUES (NULL, 'CDA dist', '2024-01-01', '2024-01-12', '12');
INSERT INTO `ga_class` (`Class_ID`, `Class_Name`, `Class_Start`, `Class_Finish`, `Class_Places`) VALUES (NULL, 'DTI 1', '2024-01-01', '2024-01-12', '12');
INSERT INTO `ga_class` (`Class_ID`, `Class_Name`, `Class_Start`, `Class_Finish`, `Class_Places`) VALUES (NULL, 'DTI 2', '2024-01-01', '2024-01-12', '12');
INSERT INTO `ga_class` (`Class_ID`, `Class_Name`, `Class_Start`, `Class_Finish`, `Class_Places`) VALUES (NULL, 'CDA PSH OPS', '2024-01-01', '2024-01-12', '10');
INSERT INTO `ga_user` (`User_ID`, `User_FirstName`, `User_LastName`, `User_Password`, `User_Activated`, `User_Email`, `Role_ID`) VALUES (NULL, 'Killian', 'Vanhove', 'KVpassword', '1', 'kv@simp.fr', '6');
INSERT INTO `ga_user` (`User_ID`, `User_FirstName`, `User_LastName`, `User_Password`, `User_Activated`, `User_Email`, `Role_ID`) VALUES (NULL, 'Salomé', 'Burteaux', 'SBpassword', '1', 'SB@simp.fr', '6');
INSERT INTO `ga_user` (`User_ID`, `User_FirstName`, `User_LastName`, `User_Password`, `User_Activated`, `User_Email`, `Role_ID`) VALUES (NULL, 'Aubin', 'Josi', 'AJpassword', '1', 'AJ@simp.fr', '6');
INSERT INTO `ga_user` (`User_ID`, `User_FirstName`, `User_LastName`, `User_Password`, `User_Activated`, `User_Email`, `Role_ID`) VALUES (NULL, 'Yoan', 'Jambon', 'YJpassword', '1', 'YJ@simp.fr', '6');
INSERT INTO `ga_user` (`User_ID`, `User_FirstName`, `User_LastName`, `User_Password`, `User_Activated`, `User_Email`, `Role_ID`) VALUES (NULL, 'Clement', 'Saulle', 'CSpassword', '1', 'CS@simp.fr', '6');
INSERT INTO `userhasclass` (`Class_ID`, `User_ID`) VALUES ('8', '2'),('8', '3'), ('8', '4'),('8', '5'), ('8', '6');
